#!/usr/bin/env node
// Stamp the current core (src/core.css, src/core.js, src/readme.txt with src/definition-reference.md)
// into Carryall HTML files, and generate the Copilot knowledge file.
// Only the core blocks, the README comment and the data-ca-core attribute are touched;
// app code (#ca-app, #ca-app-css) and data (#ca-data) are left exactly as they are.
//
//   node tools/sync-core.mjs                 # template + every examples/**/*.html
//   node tools/sync-core.mjs path/to/app.html [more.html ...]
//   node tools/sync-core.mjs --check         # exit 1 if any file is out of date

import { readFileSync, writeFileSync, readdirSync, statSync, mkdirSync } from 'node:fs';
import { join, dirname, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const read = p => readFileSync(join(root, p), 'utf8').replace(/\r\n/g, '\n');

const css = read('src/core.css').trimEnd();
const js = read('src/core.js').trimEnd();
const version = /const CORE_VERSION = '([^']+)'/.exec(js)?.[1];
if (!version) throw new Error('CORE_VERSION not found in src/core.js');
const definitionRef = read('src/definition-reference.md').trimEnd();
const readme = read('src/readme.txt').replaceAll('{{CORE_VERSION}}', version).replace('{{DEFINITION_REFERENCE}}', () => definitionRef).trimEnd();

// Guard against content that would break out of its container when inlined.
const bad = [
  [js, /<\/script|<!--/i, 'src/core.js must not contain "</script" or "<!--"'],
  [css, /<\/style/i, 'src/core.css must not contain "</style"'],
  [readme, /--/, 'src/readme.txt must not contain "--" (it lives inside an HTML comment)'],
];
for (const [text, re, msg] of bad) if (re.test(text)) throw new Error(msg);

function walk(dir) {
  const out = [];
  for (const name of readdirSync(dir)) {
    if (name.startsWith('_')) continue; // e.g. _saved/ test captures from dev-server
    const p = join(dir, name);
    if (statSync(p).isDirectory()) out.push(...walk(p));
    else if (name.endsWith('.html')) out.push(p);
  }
  return out;
}

const args = process.argv.slice(2);
const check = args.includes('--check');
let files = args.filter(a => !a.startsWith('--'));
if (!files.length) files = [join(root, 'carryall.html'), ...walk(join(root, 'examples'))];

// Blocks match only at the start of a line: the (indented) README mentions these tags too.
const blocks = [
  [/^<!--ca-readme[\s\S]*?-->/m, () => `<!--ca-readme\n${readme}\n-->`],
  [/^<style id="ca-core-css">[\s\S]*?<\/style>/m, () => `<style id="ca-core-css">\n${css}\n</style>`],
  [/^<script id="ca-core">[\s\S]*?<\/script>/m, () => `<script id="ca-core">\n${js}\n</script>`],
  [/^(<html\b[^>]*?) data-ca-core="[^"]*"/m, (_, open) => `${open} data-ca-core="${version}"`],
];

let stale = 0;
for (const f of files) {
  const before = readFileSync(f, 'utf8');
  let after = before;
  for (const [re, replacer] of blocks) {
    if (!re.test(after)) throw new Error(`${relative(root, f)}: missing block ${re}`);
    after = after.replace(re, replacer); // function form: no $-pattern surprises
  }
  if (after === before) { console.log(`  up to date  ${relative(root, f)}`); continue; }
  stale++;
  if (check) console.log(`  STALE       ${relative(root, f)}`);
  else { writeFileSync(f, after); console.log(`  synced      ${relative(root, f)} → core ${version}`); }
}

// Copilot knowledge file: the tool definition reference plus two complete example definitions,
// always matching this core. JSON only: no JavaScript, so Copilot is never tempted to write any.
// Upload it as agent knowledge, or attach it to a chat (see docs/CREATE-A-TOOL-WITH-COPILOT.md).
const inline = v => (v === null || typeof v !== 'object' ? JSON.stringify(v)
  : Array.isArray(v) ? '[' + v.map(inline).join(', ') + ']'
  : Object.keys(v).length ? '{ ' + Object.entries(v).map(([k, x]) => JSON.stringify(k) + ': ' + inline(x)).join(', ') + ' }' : '{}');
const pretty = (v, indent = '') => {
  const one = inline(v);
  if (v === null || typeof v !== 'object' || one.length + indent.length <= 100) return one;
  const inner = indent + '  ';
  return Array.isArray(v) ? '[\n' + v.map(x => inner + pretty(x, inner)).join(',\n') + '\n' + indent + ']'
    : '{\n' + Object.entries(v).map(([k, x]) => inner + JSON.stringify(k) + ': ' + pretty(x, inner)).join(',\n') + '\n' + indent + '}';
};
function exampleSpec(file) {
  const html = readFileSync(join(root, 'examples', file), 'utf8').replace(/\r\n/g, '\n');
  const m = /^<script type="application\/json" id="ca-spec">\n([\s\S]*?)\n<\/script>/m.exec(html);
  if (!m) throw new Error(`examples/${file}: no #ca-spec block for the Copilot knowledge file`);
  const spec = JSON.parse(m[1]);
  delete spec.home; delete spec.versionUrl; // local test addresses: not something to copy
  return pretty(spec);
}
const brief = `# Carryall tool definitions: reference for Copilot (core ${version})

Generated by tools/sync-core.mjs from src/definition-reference.md and the example tools. Do not edit by hand.

You write Carryall **tool definitions**: JSON only. The person pastes the definition into the Carryall
tool builder (the blank template \`carryall.html\` opened in Edge or Chrome), which checks it, previews
it and downloads the finished tool. Never write JavaScript, HTML or CSS for a Carryall tool, and never
invent keys or functions that this reference does not list.

${definitionRef}

## Worked example: design review tracker

Three linked tables, seeded rows, formulas across links, checks, onSave rules, a dashboard, a matrix and
a printable sheet. A complete, valid definition.

\`\`\`json
${exampleSpec('review-tracker.html')}
\`\`\`

## Worked example: asset register

A tool that has been changed twice since release: schemaVersion 3 with two migrations and a test for
each old version. A complete, valid definition.

\`\`\`json
${exampleSpec('asset-register.html')}
\`\`\`
`;
const briefPath = join(root, 'docs', 'copilot', 'carryall-reference.md');
let briefOld = '';
try { briefOld = readFileSync(briefPath, 'utf8'); } catch { /* first run */ }
if (briefOld === brief) console.log(`  up to date  ${relative(root, briefPath)}`);
else {
  stale++;
  if (check) console.log(`  STALE       ${relative(root, briefPath)}`);
  else { mkdirSync(dirname(briefPath), { recursive: true }); writeFileSync(briefPath, brief); console.log(`  generated   ${relative(root, briefPath)}`); }
}
if (check && stale) process.exit(1);
